
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import java.io.FileReader;
import java.io.IOException;

public final class Administrator extends javax.swing.JFrame {

    private final String adminName;
    private final String usname;
    private static final String DEFAULT_ACCOUNT_OPTION = "Select Account";
    private String Disabled_Feature; // Instance field for the disabled feature

    private static final String[] FILE_PATH = {"src/QuizData.json", "src/UserData.json"};

    public Administrator(String adminName, String usname) {
        initComponents();
        this.adminName = adminName;
        this.usname = usname;

        configureDisableFeaturesTable();
        populateUserSelection_disable_account_feature();
        populateAccountComboBox();
        welcomeMessage.setText("Welcome, Administrator " + adminName + "!"); // Dynamic message
        Current_Disabled_Feature();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin = new javax.swing.JPanel();
        welcomeMessage = new javax.swing.JLabel();
        editAccountButton = new javax.swing.JButton();
        disableFeatureButton = new javax.swing.JButton();
        menubutton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        Panes = new javax.swing.JTabbedPane();
        edit_account_pane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        saveEditButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        typeSelection = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newUsernameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JTextField();
        accountToEditSelection = new javax.swing.JComboBox<>();
        menu_pane = new javax.swing.JPanel();
        leaderboardButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        createQuizButton = new javax.swing.JButton();
        editQuizButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        deleteQuizButton = new javax.swing.JButton();
        disable_account_feature_pane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        accountToDisableSelection = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        statusSelection = new javax.swing.JComboBox<>();
        saveStatusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        disableFeaturesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin.setBackground(new java.awt.Color(102, 102, 102));

        welcomeMessage.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        welcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        welcomeMessage.setText("Welcome Administrator");

        editAccountButton.setBackground(new java.awt.Color(204, 204, 204));
        editAccountButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        editAccountButton.setText("Edit a Account");
        editAccountButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountButtonActionPerformed(evt);
            }
        });

        disableFeatureButton.setBackground(new java.awt.Color(204, 204, 204));
        disableFeatureButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        disableFeatureButton.setText("Disable a Account's Feature");
        disableFeatureButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        disableFeatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableFeatureButtonActionPerformed(evt);
            }
        });

        menubutton.setBackground(new java.awt.Color(204, 204, 204));
        menubutton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        menubutton.setText("Menu");
        menubutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuttonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(204, 204, 204));
        logoutButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 0, 0));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin);
        admin.setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disableFeatureButton)
                    .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adminLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(welcomeMessage))
                        .addGroup(adminLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(welcomeMessage)
                .addGap(27, 27, 27)
                .addComponent(menubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(editAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(disableFeatureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        getContentPane().add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 466));

        edit_account_pane.setBackground(new java.awt.Color(204, 204, 204));
        edit_account_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Farah", 1, 13)); // NOI18N
        jLabel3.setText("Edit  an  Account Tab");
        edit_account_pane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        saveEditButton.setText("Save Changes");
        saveEditButton.setEnabled(false);
        saveEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEditButtonActionPerformed(evt);
            }
        });
        edit_account_pane.add(saveEditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 130, 40));

        jLabel4.setFont(new java.awt.Font("Farah", 0, 13)); // NOI18N
        jLabel4.setText("List  of Account");
        edit_account_pane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 30));

        typeSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Game Master", "Player", "Administrator" }));
        typeSelection.setEnabled(false);
        typeSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeSelectionActionPerformed(evt);
            }
        });
        edit_account_pane.add(typeSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 160, 30));

        jLabel7.setText("Account's Type:");
        edit_account_pane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, 30));

        jLabel5.setText("----------------------");
        edit_account_pane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel6.setText("New Username :");
        edit_account_pane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 30));

        newUsernameField.setEnabled(false);
        edit_account_pane.add(newUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 160, 30));

        jLabel8.setText("----------------------");
        edit_account_pane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel9.setText("New Password :");
        edit_account_pane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 30));

        newPasswordField.setEnabled(false);
        edit_account_pane.add(newPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 160, 30));

        accountToEditSelection.setMaximumRowCount(100);
        accountToEditSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account" }));
        accountToEditSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountToEditSelectionActionPerformed(evt);
            }
        });
        edit_account_pane.add(accountToEditSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 160, 30));

        Panes.addTab("tab1", edit_account_pane);

        menu_pane.setBackground(new java.awt.Color(204, 204, 204));

        leaderboardButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        leaderboardButton.setText("Leaderboard");
        leaderboardButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leaderboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboardButtonActionPerformed(evt);
            }
        });

        historyButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        historyButton.setText("History");
        historyButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });

        createQuizButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        createQuizButton.setText("Create Quiz");
        createQuizButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createQuizButtonActionPerformed(evt);
            }
        });

        editQuizButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        editQuizButton.setText("Edit Quiz");
        editQuizButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editQuizButtonActionPerformed(evt);
            }
        });

        profileButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        profileButton.setText("Profile");
        profileButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        deleteQuizButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        deleteQuizButton.setText("Delete Quiz");
        deleteQuizButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteQuizButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu_paneLayout = new javax.swing.GroupLayout(menu_pane);
        menu_pane.setLayout(menu_paneLayout);
        menu_paneLayout.setHorizontalGroup(
            menu_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_paneLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(menu_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaderboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
        );
        menu_paneLayout.setVerticalGroup(
            menu_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_paneLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(leaderboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(deleteQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(editQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(createQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        Panes.addTab("tab3", menu_pane);

        disable_account_feature_pane.setBackground(new java.awt.Color(204, 204, 204));
        disable_account_feature_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Damascus", 1, 18)); // NOI18N
        jLabel2.setText("Disable  an  Account's Feature");
        disable_account_feature_pane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 29, -1, 31));

        jLabel11.setText("List of Account");
        disable_account_feature_pane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 101, -1, 26));

        accountToDisableSelection.setFont(new java.awt.Font("Farah", 0, 13)); // NOI18N
        accountToDisableSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account" }));
        accountToDisableSelection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        accountToDisableSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountToDisableSelectionActionPerformed(evt);
            }
        });
        disable_account_feature_pane.add(accountToDisableSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 101, 180, 30));

        jLabel13.setFont(new java.awt.Font("Damascus", 1, 14)); // NOI18N
        jLabel13.setText("Feature");
        disable_account_feature_pane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 149, -1, 29));

        jLabel1.setText("Account Status:");
        disable_account_feature_pane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 328, -1, 32));

        statusSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accessible", "Disabled" }));
        statusSelection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        disable_account_feature_pane.add(statusSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 366, 115, 35));

        saveStatusButton.setFont(new java.awt.Font("Farah", 1, 13)); // NOI18N
        saveStatusButton.setText("Save");
        saveStatusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStatusButtonActionPerformed(evt);
            }
        });
        disable_account_feature_pane.add(saveStatusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 366, 115, 35));

        disableFeaturesTable.setFont(new java.awt.Font("Farah", 1, 13)); // NOI18N
        disableFeaturesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Features", "Check to Disable"
            }
        ));
        jScrollPane1.setViewportView(disableFeaturesTable);

        disable_account_feature_pane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 184, 312, 126));

        Panes.addTab("tab2", disable_account_feature_pane);

        getContentPane().add(Panes, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, -44, 460, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountButtonActionPerformed

        Panes.setSelectedIndex(1);

    }//GEN-LAST:event_editAccountButtonActionPerformed

    private void disableFeatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableFeatureButtonActionPerformed

        Panes.setSelectedIndex(2);

    }//GEN-LAST:event_disableFeatureButtonActionPerformed

    private void menubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuttonActionPerformed

        Panes.setSelectedIndex(0);

    }//GEN-LAST:event_menubuttonActionPerformed

    private void saveEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditButtonActionPerformed
        String selectedAccount = (String) accountToEditSelection.getSelectedItem();
        if (selectedAccount.equals(DEFAULT_ACCOUNT_OPTION)) {
            JOptionPane.showMessageDialog(this, "Please select an account to edit.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String newUsername = newUsernameField.getText().trim();
        String newPassword = newPasswordField.getText().trim();
        String newType = (String) typeSelection.getSelectedItem();

        try (FileReader reader = new FileReader(FILE_PATH[1])) {
            JSONParser parser = new JSONParser();
            JSONObject data = (JSONObject) parser.parse(reader);
            JSONArray accounts = (JSONArray) data.get("Accounts");

            for (Object obj : accounts) {
                JSONObject account = (JSONObject) obj;
                if (account.get("username").equals(selectedAccount)) {
                    if (!newUsername.isEmpty()) {
                        account.put("username", newUsername);
                    }
                    if (!newPassword.isEmpty()) {
                        account.put("password", newPassword);
                    }
                    if (newType != null) {
                        account.put("type", newType);
                    }
                    break;
                }
            }

            try (FileWriter writer = new FileWriter(FILE_PATH[1])) {
                writer.write(data.toJSONString());
            }

            JOptionPane.showMessageDialog(this, "Account updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            populateUserSelection();
            resetEditAccountFields();

        } catch (IOException | ParseException e) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, "Error updating account", e);
            JOptionPane.showMessageDialog(this, "An error occurred. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveEditButtonActionPerformed

    private void leaderboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardButtonActionPerformed
        this.dispose(); // Dispose the current JFrame
        // Navigate to the Leaderboard with the Game Master's details
        new Leaderboard(adminName, null, null, usname).setVisible(true);
    }//GEN-LAST:event_leaderboardButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        this.dispose(); // Dispose the current JFrame
        // Corrected the argument order and roles passed to the History class
        new History(adminName, usname, null, null).setVisible(true);
    }//GEN-LAST:event_historyButtonActionPerformed

    private void createQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createQuizButtonActionPerformed
        this.dispose(); // Dispose the current JFrame
        new CreateQuiz(adminName, usname, null).setVisible(true);
    }//GEN-LAST:event_createQuizButtonActionPerformed

    private void editQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editQuizButtonActionPerformed
        // Pass an empty string for gameMasterName if it's not applicable
        new EditQuizTable(adminName, "", usname, null).setVisible(true);
        this.dispose(); // Dispose the current JFrame
    }//GEN-LAST:event_editQuizButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new SignIn(usname, "pass").setVisible(true); // Open the SignIn JFrame
        this.dispose(); // Dispose this JFrame and release resources
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void accountToEditSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountToEditSelectionActionPerformed
        // Check if the action listener should be ignored (i.e., during population)
        if (populateComboBox) {
            return;
        }

        String selectedAccount = (String) accountToEditSelection.getSelectedItem(); // Fixed to use accountToEditSelection

        // Check if no item is selected or the default "Select Account" is selected
        if (selectedAccount == null || selectedAccount.equals(DEFAULT_ACCOUNT_OPTION)) {
            disableEditFields(); // Disable all edit fields
            JOptionPane.showMessageDialog(this, "Please select an account to edit.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (FileReader reader = new FileReader(FILE_PATH[1])) {
            // Parse the JSON file
            JSONParser parser = new JSONParser();
            JSONObject data = (JSONObject) parser.parse(reader);
            JSONArray accounts = (JSONArray) data.get("Accounts");

            for (Object obj : accounts) {
                JSONObject account = (JSONObject) obj;

                // Find the selected account and populate fields
                if (account.get("username").equals(selectedAccount)) {
                    newUsernameField.setText((String) account.get("username"));
                    newPasswordField.setText((String) account.get("password"));
                    typeSelection.setSelectedItem((String) account.get("type"));

                    enableEditFields(); // Enable fields for editing
                    return;
                }
            }
        } catch (IOException | ParseException e) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Error loading account details. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accountToEditSelectionActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        // Pass the current username to the Profile class
        new Profile(adminName).setVisible(true); // Pass the adminName as the username
        this.dispose(); // Dispose the current JFrame
    }//GEN-LAST:event_profileButtonActionPerformed

    private void accountToDisableSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountToDisableSelectionActionPerformed
        if (populateComboBox) {
            return;
        }

        String selectedAccount = (String) accountToDisableSelection.getSelectedItem();
        if (selectedAccount == null || selectedAccount.equals("Select Account")) {
            JOptionPane.showMessageDialog(this, "Please select an account to edit.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (FileReader reader = new FileReader(FILE_PATH[1])) {
            JSONParser parser = new JSONParser();
            JSONObject data = (JSONObject) parser.parse(reader);
            JSONArray accounts = (JSONArray) data.get("Accounts");

            for (Object obj : accounts) {
                JSONObject account = (JSONObject) obj;
                if (account.get("username").equals(selectedAccount)) {
                    String type = (String) account.get("type");
                    String status = (String) account.get("status");
                    statusSelection.setSelectedItem(status);
                    populateDisableFeaturesTable(type, account);
                    break;
                }
            }
        } catch (IOException | ParseException e) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Error loading account details. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accountToDisableSelectionActionPerformed

    private void saveStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStatusButtonActionPerformed
        String selectedAccount = (String) accountToDisableSelection.getSelectedItem();
        if (selectedAccount == null || selectedAccount.equals("Select Account")) {
            JOptionPane.showMessageDialog(this, "Please select an account to edit.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String newStatus = (String) statusSelection.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) disableFeaturesTable.getModel();
        JSONArray disabledFeatures = new JSONArray();

        for (int i = 0; i < model.getRowCount(); i++) {
            Object checkboxValue = model.getValueAt(i, 1); // Ensure the checkbox value is non-null
            if (checkboxValue instanceof Boolean && (Boolean) checkboxValue) {
                disabledFeatures.add((String) model.getValueAt(i, 0));
            }
        }

        try (FileReader reader = new FileReader(FILE_PATH[1])) {
            JSONParser parser = new JSONParser();
            JSONObject data = (JSONObject) parser.parse(reader);
            JSONArray accounts = (JSONArray) data.get("Accounts");

            boolean changesMade = false;

            for (Object obj : accounts) {
                JSONObject account = (JSONObject) obj;
                if (account.get("username").equals(selectedAccount)) {
                    if (!account.get("status").equals(newStatus)) {
                        account.put("status", newStatus);
                        changesMade = true;
                    }
                    if (!account.get("disabledFeature").equals(disabledFeatures)) {
                        account.put("disabledFeature", disabledFeatures);
                        changesMade = true;
                    }
                    break;
                }
            }

            if (!changesMade) {
                JOptionPane.showMessageDialog(this, "Nothing was changed.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            try (FileWriter writer = new FileWriter(FILE_PATH[1])) {
                writer.write(data.toJSONString());
                writer.flush();
            }

            JOptionPane.showMessageDialog(this, "Changes saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException | ParseException e) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Error saving changes. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveStatusButtonActionPerformed

    private void deleteQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteQuizButtonActionPerformed
        new DeleteQuiz(adminName, null, usname).setVisible(true); // Open the new JFrame
        this.dispose(); // Dispose the current JFrame
    }//GEN-LAST:event_deleteQuizButtonActionPerformed

    private void typeSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeSelectionActionPerformed

    private void populateUserSelection_disable_account_feature() {
        try (FileReader reader = new FileReader(FILE_PATH[1])) {
            JSONParser parser = new JSONParser();
            JSONObject data = (JSONObject) parser.parse(reader);

            if (data == null || !data.containsKey("Accounts")) {
                JOptionPane.showMessageDialog(this, "No accounts found in the file.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            JSONArray accounts = (JSONArray) data.get("Accounts");

            populateComboBox = true;
            accountToDisableSelection.removeAllItems();
            accountToDisableSelection.addItem("Select Account");

            for (Object obj : accounts) {
                JSONObject account = (JSONObject) obj;
                accountToDisableSelection.addItem((String) account.get("username"));
            }
            populateComboBox = false;
        } catch (IOException | ParseException e) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Error loading accounts. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void populateUserSelection() {
        try (FileReader reader = new FileReader(FILE_PATH[1])) {
            // Parse the JSON file
            JSONParser parser = new JSONParser();
            JSONObject data = (JSONObject) parser.parse(reader);
            JSONArray accounts = (JSONArray) data.get("Accounts");

            populateComboBox = true; // Set flag to true to prevent action listener from firing
            accountToEditSelection.removeAllItems(); // Clear current items
            accountToEditSelection.addItem("Select Account"); // Default option

            for (Object obj : accounts) {
                JSONObject account = (JSONObject) obj;
                accountToEditSelection.addItem((String) account.get("username"));
            }
            populateComboBox = false; // Reset flag after populating JComboBox
        } catch (IOException | ParseException e) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Error loading accounts. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void resetEditAccountFields() {
        accountToEditSelection.setSelectedIndex(0); // Reset to "Select Account"
        newUsernameField.setText("");
        newPasswordField.setText("");
        typeSelection.setSelectedIndex(0); // Reset the type selection
        disableEditFields();
    }

    private void disableEditFields() {
        newUsernameField.setEnabled(false);
        newPasswordField.setEnabled(false);
        typeSelection.setEnabled(false);
        saveEditButton.setEnabled(false);
    }

    private void enableEditFields() {
        newUsernameField.setEnabled(true);
        newPasswordField.setEnabled(true);
        typeSelection.setEnabled(true);
        saveEditButton.setEnabled(true);
    }

    private void populateDisableFeaturesTable(String type, JSONObject account) {
        DefaultTableModel model = (DefaultTableModel) disableFeaturesTable.getModel();
        model.setRowCount(0);

        String[] features = switch (type) {
            case "Player" ->
                new String[]{"Start Game", "Leaderboard", "History", "Profile"};
            case "Game Master" ->
                new String[]{"Create Quiz", "Delete Quiz", "Edit Quiz", "Leaderboard", "History", "Profile"};
            case "Administrator" ->
                new String[]{"Create Quiz", "Delete Quiz", "Edit Quiz", "Leaderboard", "History", "Profile", "Edit Account", "Disable Feature"};
            default ->
                new String[]{};
        };

        JSONArray disabledFeatures = account.get("disabledFeature") instanceof JSONArray
                ? (JSONArray) account.get("disabledFeature")
                : new JSONArray();

        for (String feature : features) {
            model.addRow(new Object[]{feature, disabledFeatures.contains(feature)});
        }
    }

    private void configureDisableFeaturesTable() {
        disableFeaturesTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"Features", "Check to Disable"}
        ) {
            Class<?>[] columnTypes = new Class<?>[]{String.class, Boolean.class};

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnTypes[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 1; // Only the checkbox column is editable
            }
        });
    }

    private boolean populateComboBox = false; // Flag to prevent triggering action listener during population

    private void populateAccountComboBox() {
        populateComboBox = true; // Prevent triggering action listener during population
        accountToEditSelection.removeAllItems(); // Clear existing items

        // Add a default placeholder item
        accountToEditSelection.addItem(DEFAULT_ACCOUNT_OPTION);

        try (FileReader reader = new FileReader(FILE_PATH[1])) {
            JSONParser parser = new JSONParser();
            JSONObject data = (JSONObject) parser.parse(reader);

            if (data == null || !data.containsKey("Accounts")) {
                JOptionPane.showMessageDialog(this, "No accounts found in the file.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            JSONArray accounts = (JSONArray) data.get("Accounts");
            for (Object obj : accounts) {
                JSONObject account = (JSONObject) obj;
                String username = (String) account.get("username");

                if (username != null && !username.trim().isEmpty()) {
                    accountToEditSelection.addItem(username);
                }
            }
        } catch (IOException | ParseException e) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, "Error populating accounts", e);
            JOptionPane.showMessageDialog(this, "Failed to load accounts. Please check the file and try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        populateComboBox = false; // Allow action listener to be triggered again
    }

    public void Current_Disabled_Feature() {
        Disabled_Feature = ""; // Default value in case of error or missing data

        try (FileReader reader = new FileReader("src/UserData.json")) {
            // Parse the JSON file
            JSONParser parser = new JSONParser();
            JSONObject data = (JSONObject) parser.parse(reader);

            // Get the "Accounts" array
            JSONArray accounts = (JSONArray) data.get("Accounts");

            // Search for the account matching the current username
            for (Object obj : accounts) {
                JSONObject account = (JSONObject) obj;
                String username = (String) account.get("username");

                if (username.equals(adminName)) {
                    // Get the disabledFeature value
                    Object disabledFeatureObject = account.get("disabledFeature");

                    // Reset all buttons to enabled (default state)
                    leaderboardButton.setEnabled(true);
                    historyButton.setEnabled(true);
                    createQuizButton.setEnabled(true);
                    deleteQuizButton.setEnabled(true);
                    editQuizButton.setEnabled(true);
                    profileButton.setEnabled(true);

                    // Check if disabledFeature is an array or single string
                    switch (disabledFeatureObject) {
                        case JSONArray disabledFeaturesArray -> {

                            // Disable buttons based on the array contents
                            for (Object feature : disabledFeaturesArray) {
                                String featureName = (String) feature;

                                switch (featureName) {
                                    case "Leaderboard" ->
                                        leaderboardButton.setEnabled(false);
                                    case "History" ->
                                        historyButton.setEnabled(false);
                                    case "CreateQuiz" ->
                                        createQuizButton.setEnabled(false);
                                    case "DeleteQuiz" ->
                                        deleteQuizButton.setEnabled(false);
                                    case "EditQuiz" ->
                                        editQuizButton.setEnabled(false);
                                    case "Profile" ->
                                        profileButton.setEnabled(false);
                                }
                            }
                        }
                        case String string -> {
                            // Handle disabledFeature as a single string (fallback for older format)
                            Disabled_Feature = string;

                            switch (Disabled_Feature) {
                                case "None" -> {
                                    // All buttons remain enabled
                                }
                                case "Leaderboard" ->
                                    leaderboardButton.setEnabled(false);
                                case "History" ->
                                    historyButton.setEnabled(false);
                                case "CreateQuiz" ->
                                    createQuizButton.setEnabled(false);
                                case "DeleteQuiz" ->
                                    deleteQuizButton.setEnabled(false);
                                case "EditQuiz" ->
                                    editQuizButton.setEnabled(false);
                                case "Profile" ->
                                    profileButton.setEnabled(false);
                            }
                        }
                        default -> {
                        }
                    }

                    break; // Exit loop once the matching account is found
                }
            }
        } catch (IOException | ParseException e) {
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Administrator("Admin", "User").setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Panes;
    private javax.swing.JComboBox<String> accountToDisableSelection;
    private javax.swing.JComboBox<String> accountToEditSelection;
    private javax.swing.JPanel admin;
    private javax.swing.JButton createQuizButton;
    private javax.swing.JButton deleteQuizButton;
    private javax.swing.JButton disableFeatureButton;
    private javax.swing.JTable disableFeaturesTable;
    private javax.swing.JPanel disable_account_feature_pane;
    private javax.swing.JButton editAccountButton;
    private javax.swing.JButton editQuizButton;
    private javax.swing.JPanel edit_account_pane;
    private javax.swing.JButton historyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leaderboardButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel menu_pane;
    private javax.swing.JButton menubutton;
    private javax.swing.JTextField newPasswordField;
    private javax.swing.JTextField newUsernameField;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton saveEditButton;
    private javax.swing.JButton saveStatusButton;
    private javax.swing.JComboBox<String> statusSelection;
    private javax.swing.JComboBox<String> typeSelection;
    private javax.swing.JLabel welcomeMessage;
    // End of variables declaration//GEN-END:variables
}
